# Generate a GitHub Actions workflow to deploy this React web application to GitHub Pages
# This workflow will run on every push to the master branch
# For more information see: https://help.github.com/actions/language-and-framework-guides/deploying-a-react-app-to-github-pages

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  Echo:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Hello World
        run: echo "Hello World"
      


###