# Generate a GitHub Actions workflow to deploy this React web application to GitHub Pages
# This workflow will run on every push to the master branch
# For more information see: https://help.github.com/actions/language-and-framework-guides/deploying-a-react-app-to-github-pages

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  Deploy_to_GitHub_Pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Code
        run: |
          npm ci
          npm run build
      
      - name: Deploy to GH Pages
        run: |
          git config --global user.email ${{ secrets.GH_EMAIL }}
          git config --global user.name ${{ secrets.GH_USERNAME }}
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/first-react-app.git
          npm run deploy


###